language: c
cache: ccache
dist: trusty
notifications:
  email: false
branches:
  only:
    - master
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libssl-dev
    - libev-dev
    - libc-ares-dev
    - libudns-dev
    - libstdc++-4.9-dev
env:
- SDK_URL=https://downloads.openwrt.org/releases/17.01.4/targets/ar71xx/nand/lede-sdk-17.01.4-ar71xx-nand_gcc-5.4.0_musl-1.1.16.Linux-x86_64.tar.xz
install:
- export TAG=$(sed -n 's/.*lede-sdk-17.01.4-\(.*\)_gcc.*/\1/p' <<< $SDK_URL | awk -F- '{print $1}')
- wget $SDK_URL
- tar xf $(basename $SDK_URL)
- cd *$TAG*
before_script:
# Shadowsocks
- git clone https://github.com/shadowsocks/luci-app-shadowsocks package/luci-app-shadowsocks
- git clone https://github.com/shadowsocks/openwrt-shadowsocks package/shadowsocks-libev
- git clone https://github.com/aa65535/openwrt-simple-obfs package/simple-obfs
# Misc
- git clone https://github.com/aa65535/openwrt-chinadns package/chinadns
- git clone https://github.com/aa65535/openwrt-dns-forwarder package/dns-forwarder
- git clone https://github.com/aa65535/openwrt-dist-luci package/openwrt-dist-luci
# Pdnsd
- git clone https://github.com/simonsmh/openwrt-pdnsd package/pdnsd
- git clone https://github.com/AlexZhuo/luci-app-pdnsd package/luci-app-pdnsd
# Vlmcsd
- git clone https://github.com/mchome/openwrt-vlmcsd package/vlmcsd
- git clone https://github.com/mchome/luci-app-vlmcsd package/luci-app-vlmcsd
# Dependency
- git clone https://github.com/shadowsocks/openwrt-feeds package/custom
- pushd package/openwrt-dist-luci/tools/po2lmo ; make && sudo make install ; popd
- ./scripts/feeds update -a
- ./scripts/feeds install libopenssl
script:
- make defconfig
- make prereq V=s
# Compile packages
- make package/luci-app-shadowsocks/compile V=s
- make package/shadowsocks-libev/compile V=s
- make package/simple-obfs/compile V=s
- make package/chinadns/compile V=s
- make package/dns-forwarder/compile V=s
- make package/openwrt-dist-luci/compile V=s
- make package/pdnsd/compile V=s
- make package/luci-app-pdnsd/compile V=s
- make package/vlmcsd/compile V=s
- make package/luci-app-vlmcsd/compile V=s
# Generate packages.gz
- ./staging_dir/host/bin/usign -G -s ./key-build -p ./key-build.pub -c "Local build key"
- make package/index V=s
after_success:
- cd bin
- git init
- git config user.name "bot"
- git config user.email "bot@github.com"
- git add .
- git commit -m "$TAG"
- git push --force --quiet "https://${GitHub_Token}@github.com/simonsmh/openwrt-dist.git" HEAD:$TAG
